{"Modified": "2022-07-12T17:42:00", "Published": "2020-05-07T20:15:00", "access": {"authentication": "SINGLE", "complexity": "LOW", "vector": "NETWORK"}, "assigner": "psirt@us.ibm.com", "capec": [], "cvss": 9.0, "cvss-time": "2022-07-12T17:42:00", "cvss-vector": "AV:N/AC:L/Au:S/C:C/I:C/A:C", "cwe": "NVD-CWE-noinfo", "id": "CVE-2020-4427", "impact": {"availability": "COMPLETE", "confidentiality": "COMPLETE", "integrity": "COMPLETE"}, "last-modified": "2022-07-12T17:42:00", "references": ["https://www.ibm.com/support/pages/node/6206875", "https://exchange.xforce.ibmcloud.com/vulnerabilities/180532"], "refmap": {"confirm": ["https://www.ibm.com/support/pages/node/6206875"], "xf": ["ibm-drm-cve20204427-sec-bypass (180532)"]}, "summary": "IBM Data Risk Manager 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, and 2.0.6 could allow a remote attacker to bypass security restrictions when configured with SAML authentication. By sending a specially crafted HTTP request, an attacker could exploit this vulnerability to bypass the authentication process and gain full administrative access to the system. IBM X-Force ID: 180532.", "vulnerable_configuration": [{"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*"}, {"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*"}, {"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*"}, {"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*"}, {"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*"}, {"id": "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*", "title": "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*"}], "vulnerable_configuration_cpe_2_2": [], "vulnerable_product": ["cpe:2.3:a:ibm:data_risk_manager:2.0.2:*:*:*:*:*:*:*", "cpe:2.3:a:ibm:data_risk_manager:2.0.3:*:*:*:*:*:*:*", "cpe:2.3:a:ibm:data_risk_manager:2.0.4:*:*:*:*:*:*:*", "cpe:2.3:a:ibm:data_risk_manager:2.0.5:*:*:*:*:*:*:*", "cpe:2.3:a:ibm:data_risk_manager:2.0.6:*:*:*:*:*:*:*", "cpe:2.3:a:ibm:data_risk_manager:2.0.1:*:*:*:*:*:*:*"]}